### PR TITLE
Add Gliffy Outage

### PR DESCRIPTION
**Pull request by DavidTPate**

### CODE REVIEW

**Comment by JensRantil** [comment]
470822b0cc35886234345a20f64672b910efcbfa doesn't seem to add Gliffy Outage.

**Comment by klaernie** [comment]
But 407ed16 does. Is it a problem for this repo, if two distinct features get proposed in the same PR? ;)

**Comment by JensRantil** [comment]
> Is it a problem for this repo, if two distinct features get proposed in the same PR? ;)

I'm not a maintainer, so I can't answer. ;)

**Comment by DavidTPate** [comment]
Ah, my bad looks like I accidentally had two of my proposed changes in the same branch. The other change is from #48

**Comment by danluu** [comment]
Thanks! Sorry for the delay in merging, but thanks 😄

**Pull request merged**
