### PR TITLE
Added Fastly incident link

### PR DESCRIPTION
**Pull request by pawlos**
Link for the recent Fastly post-mortem added to 'Uncategorized' section.

### CODE REVIEW

**Comment by wasylni** [comment]
there is very little detail about what exactly happened @Fastly.

**Comment by dmathieu** [comment]
I agree with @wasylni.
I don't think if this can really be named retrospective. It's more of a PR communication. It doesn't say anything about what really happened, and what they learned from it (outside of "don't break things next time").

**Comment by pawlos** [comment]
Yes, unfortunately for the moment that's the only info that was published. I hope they will extend this page soon.

**Comment by icco** [comment]
While this is definitely on the lighter side, this is still a decent incident report

**Pull request merged**
