### PR TITLE
analysis: add CCP Games devblog "Sleeping Beauty"

### PR DESCRIPTION
**Pull request by therealplato**
Devblog posted on 2017-02-15

### CODE REVIEW

**Comment by danluu** [comment]
This is interesting, but could you please move this into the "uncategorized" section?

**Comment by therealplato** [comment]
done. what's the Analysis category for?

**Comment by danluu** [comment]
Great, thanks! 

Analysis is more for commentary on failures and postmortems, like http://web.mit.edu/2.75/resources/random/How%20Complex%20Systems%20Fail.pdf. I don't think the term makes it clear how it's differentiated, but a clearer term doesn't come to mind for me.

**Comment by vmbrasseur** [comment]
Suggestion: Rename it 'Commentary on Failures & Postmortems' ?

**Comment by therealplato** [comment]
maybe `meta-analysis`

**Pull request merged**
