### PR TITLE
Add Amazon DynamoDB Service Disruption

### PR DESCRIPTION
**Pull request by farnulfo**
Add Amazon DynamoDB Service Disruption on September 20, 2015.

### CODE REVIEW

**Comment by JensRantil** [comment]
:+

**Comment by msiebuhr** [comment]
FYI: It points to the french-language version, but as they haven't translated it (yet?), it shows up as english. The english link is https://aws.amazon.com/message/5467D2/

**Comment by farnulfo** [comment]
Pull request updated with @msiebuhr remark. 
Thanks

**Comment by DavidTPate** [comment]
:+1:

**Comment by danluu** [comment]
Thanks!

**Pull request merged**
