### PR TITLE
Removed dead g+ link

### PR DESCRIPTION
**Pull request by richter-p**
archive.org does not seem to have it, either.

### CODE REVIEW

**Comment by BigEd** [comment]
How about adding in
https://www.bloomberg.com/opinion/articles/2015-09-16/how-healthcare-gov-went-so-so-wrong
instead?  Certainly the healthcare.giv fiasco deserves a postmortem entry.

One could reach Andreas Schou on twitter as theophite.

**Comment by icco** [comment]
@richter-p, mind making the change recommended by @BigEd? I'll merge after that.

**Comment by richter-p** [comment]
I'll rebase and create a new pr.

**Comment by icco** [comment]
This ended up being #126

**Pull request closed without merging**
